//! Provider usage recorded for one completed step.

/// Token and cost figures a provider reported. Fields stay optional because providers may
/// report only part of their usage, or no usage at all.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Usage {
    /// Tokens sent to the provider.
    pub input_tokens: Option<u64>,
    /// Tokens generated by the provider.
    pub output_tokens: Option<u64>,
    /// Reported USD cost in millionths of a dollar.
    pub cost_microusd: Option<u64>,
}

impl Usage {
    /// Whether the provider reported any usage figure.
    #[must_use]
    pub fn is_none(self) -> bool {
        self.input_tokens.is_none() && self.output_tokens.is_none() && self.cost_microusd.is_none()
    }

    /// Adds independently reported figures, retaining `None` only when neither side reported
    /// that figure.
    #[must_use]
    pub fn plus(self, other: Self) -> Self {
        Self {
            input_tokens: sum(self.input_tokens, other.input_tokens),
            output_tokens: sum(self.output_tokens, other.output_tokens),
            cost_microusd: sum(self.cost_microusd, other.cost_microusd),
        }
    }
}

fn sum(left: Option<u64>, right: Option<u64>) -> Option<u64> {
    match (left, right) {
        (None, None) => None,
        (left, right) => Some(
            left.unwrap_or_default()
                .saturating_add(right.unwrap_or_default()),
        ),
    }
}
