//! Self-supervision proof (T161): `ktask-rs` supervising a real queue end to
//! end, through the compiled binary, in a project that is not this one.
//!
//! [`Sandbox::build`] makes one [`tempfile::TempDir`] under the system temp
//! directory and puts everything the run can touch in it: a git repository
//! holding a small Rust workspace, its own bare `origin`, the state and
//! config homes `ktask-rs` is pointed at through `XDG_STATE_HOME` and
//! `XDG_CONFIG_HOME`, a git identity (`GIT_CONFIG_GLOBAL`), and the target
//! and home directories of the cargo that the project's quality script runs.
//! The project is registered with `init`, given a three-task queue with
//! `add --file`, and pointed at the `dummy` provider with a scenario in which
//! each task edits a file and writes a `DONE` report. The project's verify
//! gate is its two-line `scripts/quality.sh`, which really builds and tests
//! the workspace.
//!
//! The dummy provider writes files but cannot commit them, and an agent that
//! leaves its edit uncommitted is a `policy_failure` (`VISION.md` section 10),
//! so the agent's edit goes to `agent-edit-<module>.rs`, which the project
//! ignores, and the project's `format_command` applies it to the tracked
//! `<module>.rs`, where the completion set commits it. Each task has a module
//! of its own: a task's checkout starts from the project's local `HEAD`, not
//! from the commits earlier tasks published, so tasks that edited one file
//! would conflict when rebased onto the origin. That makes each task's commit
//! a distinct one, which is what the origin's tip is then compared against.
//!
//! The test then asserts what the run did — every task reached
//! `PublishedVerified` and `Done`, the origin's tip is the last candidate, and
//! the journal replays to the same state — and what it did not do: nothing was
//! written outside the sandbox, not this repository, not its remote, and not
//! the developer's own state directory.
//!
//! The one thing read from outside is the toolchain, through `PATH` (and
//! `HOME`, which `rustup` needs to find its toolchains); nothing is written
//! through either.

use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use ktask_core::{EventKind, Journal, TaskId, TaskState, apply, journal_path};

const TASKS: u32 = 3;

/// What the journey's steps return: any failure ends the test, with its own
/// message.
type Res<T = ()> = Result<T, Box<dyn std::error::Error>>;

/// The project's whole verify gate: two lines, as a project's own would be.
const QUALITY_SCRIPT: &str = "#!/bin/sh\ncargo test --quiet --offline --locked\n";

/// The workspace's lockfile, written by hand so the `--locked` gate needs no
/// network and no registry.
const CARGO_LOCK: &str = "# This file is automatically @generated by Cargo.\n\
    # It is not intended for manual editing.\n\
    version = 4\n\n[[package]]\nname = \"tally\"\nversion = \"0.1.0\"\n";

/// The module each task edits, in queue order.
const MODULES: [&str; TASKS as usize] = ["one", "two", "three"];

/// A module's source holding `count`, with the test that says so.
fn module_source(count: u32) -> String {
    format!(
        "//! A counter.

/// The count.
pub const COUNT: u32 = {count};

\
         #[cfg(test)]
mod tests {{
    #[test]
    fn counts() {{
        \
         assert_eq!(super::COUNT, {count});
    }}
}}
"
    )
}

/// `module`'s path inside the project.
fn module_path(module: &str) -> String {
    format!("crates/tally/src/{module}.rs")
}

/// Where the agent leaves its edit to `module`: ignored by the project, so
/// that leaving it is not a dirty tree.
fn agent_edit(module: &str) -> String {
    format!("agent-edit-{module}.rs")
}

/// The project's format gate: applies the agent's edit, if it left one, to
/// the module it names.
const APPLY_EDIT: &str = "for f in agent-edit-*.rs; do \
    cp \"$f\" \"crates/tally/src/${f#agent-edit-}\"; done";

/// A plan of [`TASKS`] tasks valid under `docs/CONTRACT.md` section 3.
fn plan() -> String {
    (1..=TASKS)
        .map(|n| {
            format!(
                "## Task {n}\n\n**Outcome:** the tally counts to {n}.\n\n\
                 **Done-when:** `count()` returns {n}.\n\n**Verify:** `true`\n\n\
                 **Refs:** none\n\n"
            )
        })
        .collect::<Vec<_>>()
        .concat()
}

/// `text` as a TOML basic string, quotes included.
fn toml_str(text: &str) -> Res<String> {
    // A JSON string is a valid TOML basic string.
    Ok(serde_json::to_string(text)?)
}

fn utf8(path: &Path) -> Res<&str> {
    path.to_str()
        .ok_or_else(|| format!("{} is not utf-8", path.display()).into())
}

fn stdout_of(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn stderr_of(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

/// Asserts `output` exited with `code`, showing both streams if it did not.
fn assert_exit(output: &Output, code: i32) {
    assert_eq!(
        output.status.code(),
        Some(code),
        "stdout: {}\nstderr: {}",
        stdout_of(output),
        stderr_of(output)
    );
}

/// Runs `git` in `dir`, with no identity or configuration but `config`'s, and
/// returns its stdout without the trailing newline.
fn git_in(dir: &Path, config: &Path, args: &[&str]) -> io::Result<String> {
    let output = Command::new("git")
        .args(args)
        .current_dir(dir)
        .env("GIT_CONFIG_GLOBAL", config)
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .output()?;
    if !output.status.success() {
        return Err(io::Error::other(format!(
            "git {args:?} in {} failed: {}",
            dir.display(),
            stderr_of(&output)
        )));
    }
    Ok(stdout_of(&output).trim_end().to_string())
}

/// The throwaway world: every path in it is under `root`.
struct Sandbox {
    root: tempfile::TempDir,
    project: PathBuf,
    origin: PathBuf,
    state_home: PathBuf,
    config_home: PathBuf,
    git_config: PathBuf,
    /// The project's state directory, as `init` reports it.
    state_dir: PathBuf,
    /// The commit the project began at, which the origin holds too.
    seed: String,
}

impl Sandbox {
    /// The sandbox as `init` and `add --file` leave it: registered, with the
    /// whole plan queued and nothing run.
    fn build() -> Res<Self> {
        let root = tempfile::tempdir()?;
        let base = root.path();
        let project = base.join("project");
        let origin = base.join("origin.git");
        let state_home = base.join("xdg-state");
        let config_home = base.join("xdg-config");
        let git_config = base.join("gitconfig");
        for dir in [&project, &origin, &state_home, &config_home] {
            std::fs::create_dir(dir)?;
        }
        std::fs::write(
            &git_config,
            "[user]\n\tname = Self Supervision\n\temail = self-supervision@example.invalid\n",
        )?;

        let git = |dir: &Path, args: &[&str]| git_in(dir, &git_config, args);
        git(
            &origin,
            &["init", "--quiet", "--bare", "--initial-branch=main"],
        )?;
        git(&project, &["init", "--quiet", "--initial-branch=main"])?;
        git(&project, &["remote", "add", "origin", utf8(&origin)?])?;

        std::fs::create_dir_all(project.join("scripts"))?;
        std::fs::create_dir_all(project.join("crates/tally/src"))?;
        std::fs::write(project.join("scripts/quality.sh"), QUALITY_SCRIPT)?;
        std::fs::write(project.join(".gitignore"), "/agent-edit-*.rs\n")?;
        std::fs::write(
            project.join("Cargo.toml"),
            "[workspace]\nresolver = \"2\"\nmembers = [\"crates/tally\"]\n",
        )?;
        std::fs::write(project.join("Cargo.lock"), CARGO_LOCK)?;
        std::fs::write(
            project.join("crates/tally/Cargo.toml"),
            "[package]\nname = \"tally\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        )?;
        let modules = MODULES
            .map(|module| format!("pub mod {module};\n"))
            .concat();
        std::fs::write(project.join("crates/tally/src/lib.rs"), modules)?;
        for module in MODULES {
            std::fs::write(project.join(module_path(module)), module_source(0))?;
        }
        git(&project, &["add", "."])?;
        git(&project, &["commit", "--quiet", "-m", "seed"])?;
        git(
            &project,
            &["push", "--quiet", "origin", "HEAD:refs/heads/main"],
        )?;
        let seed = git(&project, &["rev-parse", "HEAD"])?;

        let mut sandbox = Self {
            root,
            project,
            origin,
            state_home,
            config_home,
            git_config,
            state_dir: PathBuf::new(),
            seed,
        };
        sandbox.register()?;
        Ok(sandbox)
    }

    fn root(&self) -> &Path {
        self.root.path()
    }

    /// `ktask-rs` with `args`, rooted at the project and with every
    /// directory it would otherwise default to pointed into the sandbox.
    fn command(&self, args: &[&str]) -> Command {
        let mut command = Command::new(env!("CARGO_BIN_EXE_ktask-rs"));
        command
            .args(args)
            .current_dir(&self.project)
            .env("XDG_STATE_HOME", &self.state_home)
            .env("XDG_CONFIG_HOME", &self.config_home)
            .env("GIT_CONFIG_GLOBAL", &self.git_config)
            .env("GIT_CONFIG_NOSYSTEM", "1");
        command
    }

    fn run(&self, args: &[&str]) -> Res<Output> {
        Ok(self.command(args).output()?)
    }

    fn git(&self, dir: &Path, args: &[&str]) -> io::Result<String> {
        git_in(dir, &self.git_config, args)
    }

    fn origin_tip(&self) -> Res<String> {
        Ok(self.git(&self.origin, &["rev-parse", "refs/heads/main"])?)
    }

    /// `init`, then the config, the scenario and the queue.
    fn register(&mut self) -> Res {
        let init = self.run(&["init"])?;
        assert_exit(&init, 0);
        self.state_dir = stdout_of(&init)
            .lines()
            .find_map(|line| line.strip_prefix("state: "))
            .map(PathBuf::from)
            .ok_or("init did not report a state directory")?;

        std::fs::write(self.state_dir.join("config.toml"), self.config()?)?;
        std::fs::write(self.state_dir.join("scenario.toml"), self.scenario()?)?;
        let plan_path = self.state_dir.join("plan.md");
        std::fs::write(&plan_path, plan())?;
        let add = self.run(&["add", "--file", utf8(&plan_path)?])?;
        assert_exit(&add, 0);
        Ok(())
    }

    /// The project config: the `dummy` provider on this scenario, the
    /// project's own quality script as the verify gate, and a format gate
    /// that applies the agent's edit to the tracked source. The verify gate runs in a
    /// cleared environment, so the cargo inside it neither inherits this test
    /// run's `RUSTFLAGS`, coverage profile or target directory, nor writes
    /// anywhere but the sandbox.
    fn config(&self) -> Res<String> {
        let mut gate = vec![
            "env".to_string(),
            "-i".to_string(),
            format!("PATH={}", std::env::var("PATH")?),
            format!("HOME={}", std::env::var("HOME")?),
            format!("CARGO_HOME={}", self.root().join("cargo-home").display()),
            format!("CARGO_TARGET_DIR={}", self.root().join("target").display()),
        ];
        if let Ok(toolchain) = std::env::var("RUSTUP_TOOLCHAIN") {
            gate.push(format!("RUSTUP_TOOLCHAIN={toolchain}"));
        }
        gate.extend(["sh".to_string(), "scripts/quality.sh".to_string()]);
        let gate = gate
            .iter()
            .map(|arg| toml_str(arg))
            .collect::<Res<Vec<_>>>()?
            .join(", ");
        let scenario = self.state_dir.join("scenario.toml");
        Ok(format!(
            "provider = \"dummy\"\ndummy_scenario_path = {}\nverify_command = [{gate}]\n\
             format_command = [\"sh\", \"-c\", {}]\n",
            toml_str(utf8(&scenario)?)?,
            toml_str(APPLY_EDIT)?,
        ))
    }

    /// The scenario: for each task a provider probe, then an agent that
    /// leaves its module's next source in an ignored file and writes a `DONE`
    /// report.
    fn scenario(&self) -> Res<String> {
        let mut steps = Vec::new();
        for (n, module) in (1..=TASKS).zip(MODULES) {
            let report = self
                .state_dir
                .join("attempts")
                .join(n.to_string())
                .join("1")
                .join("report.md");
            steps.push("[[steps]]\noutcome = \"success\"\n\n".to_string());
            steps.push(format!(
                "[[steps]]\noutcome = \"success\"\nstdout = \"counting to {n}\\n\"\n\n\
                 [[steps.files]]\npath = {}\ncontent = {}\n\n\
                 [[steps.files]]\npath = {}\ncontent = {}\n\n",
                toml_str(&agent_edit(module))?,
                toml_str(&module_source(n))?,
                toml_str(utf8(&report)?)?,
                toml_str(&format!("KTASK_RESULT: DONE\nSummary: counted to {n}.\n"))?,
            ));
        }
        Ok(steps.concat())
    }

    /// `status --json`'s task states, in queue order.
    fn status_states(&self) -> Res<Vec<String>> {
        let status = self.run(&["status", "--json"])?;
        assert_exit(&status, 0);
        let status: serde_json::Value = serde_json::from_str(stdout_of(&status).trim())?;
        status
            .get("tasks")
            .and_then(serde_json::Value::as_array)
            .ok_or("status --json has no tasks")?
            .iter()
            .map(|task| {
                task.get("state")
                    .and_then(serde_json::Value::as_str)
                    .map(str::to_string)
                    .ok_or_else(|| "a task has no state".into())
            })
            .collect()
    }
}

/// What this repository looks like from the outside: the commit it is at and
/// every ref it holds, local and remote-tracking.
fn this_repository() -> Res<(String, String)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let git = |args: &[&str]| -> Res<String> {
        let output = Command::new("git").args(args).current_dir(dir).output()?;
        assert_exit(&output, 0);
        Ok(stdout_of(&output))
    };
    Ok((git(&["rev-parse", "HEAD"])?, git(&["for-each-ref"])?))
}

/// Each task's state after folding its journal events through the state
/// machine, and the states it passed through on the way.
fn replay(journal: &Journal) -> Res<BTreeMap<TaskId, (TaskState, Vec<&'static str>)>> {
    let mut replayed = BTreeMap::new();
    for task in journal.tasks()? {
        let mut state = TaskState::Queued;
        let mut trail = Vec::new();
        for event in journal.events_for(task.id)? {
            state = apply(&state, &event.kind)?;
            trail.push(state.name());
        }
        replayed.insert(task.id, (state, trail));
    }
    Ok(replayed)
}

/// `run` reported every task done, the last at the origin's tip, and the
/// queue drained.
fn assert_run_reported(run: &Output, tip: &str) {
    assert_exit(run, 0);
    let stdout: Vec<String> = stdout_of(run).lines().map(str::to_string).collect();
    assert_eq!(stdout.len(), TASKS as usize, "{stdout:?}");
    for (n, line) in (1..=TASKS).zip(&stdout) {
        assert!(
            line.starts_with(&format!("task {n}: done (commit ")),
            "{line}"
        );
    }
    assert_eq!(
        stdout.last().map(String::as_str),
        Some(format!("task {TASKS}: done (commit {})", &tip[..7]).as_str()),
        "the last task's commit is the origin's tip"
    );
    assert!(
        stderr_of(run).contains("run: queue drained"),
        "{}",
        stderr_of(run)
    );
}

impl Sandbox {
    /// The sandbox is a world of its own: under the system temp directory, not
    /// this repository, its own git repository, and the only remote is its
    /// own bare origin. Registration put the project's state inside it.
    fn assert_isolated(&self) -> Res {
        assert!(self.root().starts_with(std::env::temp_dir()));
        assert!(!self.root().starts_with(env!("CARGO_MANIFEST_DIR")));
        assert_eq!(
            Path::new(&self.git(&self.project, &["rev-parse", "--show-toplevel"])?)
                .canonicalize()?,
            self.project.canonicalize()?,
            "the project is a repository of its own"
        );
        assert_eq!(self.git(&self.project, &["remote"])?, "origin");
        assert_eq!(
            self.git(&self.project, &["remote", "get-url", "origin"])?,
            utf8(&self.origin)?
        );
        assert_eq!(self.origin_tip()?, self.seed);
        assert!(
            self.state_dir.starts_with(&self.state_home),
            "init registered the project under the sandbox's XDG_STATE_HOME, not {}",
            self.state_dir.display()
        );
        assert_eq!(
            self.status_states()?,
            vec!["Queued"; TASKS as usize],
            "add --file queued the whole plan"
        );
        Ok(())
    }

    /// Every task was published and confirmed against the remote, the last
    /// candidate is the origin's tip, and the origin holds each task's edit.
    fn assert_published(&self, events: &[ktask_core::Event], tip: &str) -> Res {
        let published: Vec<(&str, &str)> = events
            .iter()
            .filter_map(|event| match &event.kind {
                EventKind::PublishVerified { commit, remote_sha } => {
                    Some((commit.as_str(), remote_sha.as_str()))
                }
                _ => None,
            })
            .collect();
        assert_eq!(published.len(), TASKS as usize, "one publication per task");
        assert!(
            published.iter().all(|(commit, remote)| commit == remote),
            "each publication was confirmed against the remote: {published:?}"
        );
        assert_eq!(
            published.last().map(|(commit, _)| *commit),
            Some(tip),
            "the origin's tip is the last candidate"
        );
        assert_ne!(tip, self.seed, "the origin moved");
        assert_eq!(
            self.git(&self.origin, &["log", "--format=%s", tip])?,
            "Task 3\nTask 2\nTask 1\nseed",
            "the origin holds one commit per task, on top of the seed"
        );
        for (n, module) in (1..=TASKS).zip(MODULES) {
            assert_eq!(
                self.git(
                    &self.origin,
                    &["show", &format!("{tip}:{}", module_path(module))]
                )?,
                module_source(n).trim_end(),
                "the origin holds task {n}'s edit"
            );
        }
        assert!(
            self.root().join("target").is_dir(),
            "the gate really built the workspace, in the sandbox"
        );
        Ok(())
    }

    /// The journal replays to the same state: what `status` reports is the
    /// fold of the events, and so is the projection a rebuild produces; and
    /// with everything done, running again changes nothing.
    fn assert_replays_to_the_same_state(
        &self,
        mut journal: Journal,
        replayed: BTreeMap<TaskId, (TaskState, Vec<&'static str>)>,
        tip: &str,
    ) -> Res {
        assert_eq!(self.status_states()?, vec!["Done"; TASKS as usize]);
        let before = journal.events()?.len();
        journal.rebuild_state()?;
        let folded: BTreeMap<TaskId, TaskState> = replayed
            .into_iter()
            .map(|(task, (state, _))| (task, state))
            .collect();
        assert_eq!(
            journal.all_states()?,
            folded,
            "a rebuilt projection is the replay"
        );
        assert_eq!(self.status_states()?, vec!["Done"; TASKS as usize]);
        let again = self.run(&["run"])?;
        assert_exit(&again, 0);
        assert_eq!(stdout_of(&again), "", "nothing is left to run");
        assert_eq!(journal.events()?.len(), before, "nothing was journaled");
        assert_eq!(self.origin_tip()?, tip);
        Ok(())
    }

    /// The developer's own state directory holds nothing for the sandbox's
    /// project, and the sandbox holds only what it was given and what its own
    /// cargo made.
    fn assert_nothing_escaped(&self) -> Res {
        let suffix = self.state_dir.strip_prefix(&self.state_home)?;
        let developers_state = match std::env::var_os("XDG_STATE_HOME") {
            Some(home) => PathBuf::from(home),
            None => PathBuf::from(std::env::var("HOME")?).join(".local/state"),
        };
        assert!(
            !developers_state.join(suffix).exists(),
            "{} would be the developer's state for the sandbox project",
            developers_state.join(suffix).display()
        );
        let mut top: Vec<String> = std::fs::read_dir(self.root())?
            .map(|entry| Ok(entry?.file_name().to_string_lossy().into_owned()))
            .collect::<io::Result<_>>()?;
        top.sort();
        assert!(
            top.iter().all(|name| [
                "cargo-home",
                "gitconfig",
                "origin.git",
                "project",
                "target",
                "xdg-config",
                "xdg-state",
            ]
            .contains(&name.as_str())),
            "the sandbox holds only what it was given and what its own cargo made: {top:?}"
        );
        Ok(())
    }
}

/// The whole product supervising a queue of its own, in a project of its own.
#[test]
fn self_supervision_drains_a_three_task_queue_inside_its_sandbox() -> Res {
    let (head, refs) = this_repository()?;
    let sandbox = Sandbox::build()?;
    sandbox.assert_isolated()?;

    let run = sandbox.run(&["run"])?;
    let tip = sandbox.origin_tip()?;
    assert_run_reported(&run, &tip);

    // Every task reached PublishedVerified on its way to Done.
    let journal = Journal::open(&journal_path(&sandbox.state_dir))?;
    let replayed = replay(&journal)?;
    assert_eq!(replayed.len(), TASKS as usize);
    for (task, (state, trail)) in &replayed {
        assert_eq!(state, &TaskState::Done, "task {task}");
        let tail = &trail[trail.len() - 2..];
        assert_eq!(
            tail,
            ["PublishedVerified", "Done"],
            "task {task}: {trail:?}"
        );
    }
    sandbox.assert_published(&journal.events()?, &tip)?;
    sandbox.assert_replays_to_the_same_state(journal, replayed, &tip)?;

    // Nothing outside the sandbox was touched.
    assert_eq!(
        this_repository()?,
        (head, refs),
        "this repository has the same commit and refs as before"
    );
    sandbox.assert_nothing_escaped()
}
