[package]
name = "ktask-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "ktask-rs"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true }
ktask-core = { path = "../ktask-core", version = "0.1.0" }

[dev-dependencies]
tempfile = { workspace = true }
ktask-core = { path = "../ktask-core", version = "0.1.0", features = ["testing"] }

[lints]
workspace = true
